### ISSUE TITLE
containers-buildah 

### ISSUE THREAD

**Issue by jankleinert** [rhel-labs/learn-katacoda#111]
In what katacoda scenario did this bug occur?
https://developers.redhat.com/courses/red-hat-enterprise-linux/containers-buildah/

At what step of the scenario did this happen?
Step 5

Describe the bug
When attempting to install httpd in the working-continer (Step 5) it throws an error. "There are no enabled repos." This prevents finishing the course.

Logs or error messages
See screenshot below.
![ss](https://user-images.githubusercontent.com/651728/80515272-b3315d80-894f-11ea-910b-fb56b16091cc.png)

Originally entered by @tcloud-ua here https://github.com/openshift-labs/learn-katacoda/issues/746

**Comment by smcbrien** [comment]
Related to exhausting the subscription pool being used by the lab environment.  Subs have been added, this lab is now working as written.
