### ISSUE TITLE
sql-server-cstore

### ISSUE THREAD

**Issue by jankleinert** [rhel-labs/learn-katacoda#112]
In what katacoda scenario did this bug occur?
https://developers.redhat.com/courses/red-hat-enterprise-linux/sql-server-cstore/

At what step of the scenario did this happen?
Step 1

Describe the bug
The SQL Server background task fails due to missing dependencies and the lab is unable to execute the first step.

Logs or error messages
See screenshot below.

![80513524-cb4faf80-8944-11ea-9ee8-e4ce142fb7ae](https://user-images.githubusercontent.com/651728/80515491-0d322300-8950-11ea-8c7d-bf80ec84185f.png)

originally entered by @tcloud-ua here: https://github.com/openshift-labs/learn-katacoda/issues/745

**Comment by dpredhat** [comment]
Systems were not being subscribed to CDN correctly, lack of available entitlements on activation key. This has been resolved by adding more subs to the activation key.
