### ISSUE TITLE
ansible-getting-started

### ISSUE THREAD

**Issue by jankleinert** [rhel-labs/learn-katacoda#113]
In what katacoda scenario did this bug occur?
https://developers.redhat.com/courses/ansible/getting-started/

At what step of the scenario did this happen?
Step 2

Describe the bug
Ansible is not installed on control, host02, and host03.

Logs or error messages
See screenshot below.

![80514653-69904500-8946-11ea-9924-3f5584cb2831](https://user-images.githubusercontent.com/651728/80515766-79148b80-8950-11ea-98b7-ae2935be28ac.png)

originally entered by @tcloud-ua here: https://github.com/openshift-labs/learn-katacoda/issues/747

**Comment by dpredhat** [comment]
Issue has been verified and fixed. Closing this - Apr 28. 2.03pm et.

**Comment by smcbrien** [comment]
Systems were not being subscribed to CDN correctly, lack of available entitlements on activation key.  This has been resolved by adding more subs to the activation key.
