### ISSUE TITLE
Error Loading scenario undefined due to JSON syntax error

### ISSUE THREAD

**Issue by gundalow** [rhel-labs/learn-katacoda#140]
https://www.katacoda.com/rhel-labs shows `Error Loading scenario undefined due to JSON syntax error`

**Comment by smcbrien** [comment]
Hi John, thanks for reporting this issue!  Our customer-facing interface for these labs is:
https://lab.redhat.com

We use the katacoda-native site as our 'development' view.  And it looks like there was a formatting issue with the Japanese translation of one of the lab definition jsons.  I've fixed it, and the error should be resolved.  As an added bonus, you can now do the bcc-tools lab in Japanese if you like!

-STM
