### ISSUE TITLE
ansible-playbook command is not recognized on Ansible Web Server katacoda

### ISSUE THREAD

**Issue by jonhorton** [rhel-labs/learn-katacoda#141]
Hello!

I'm on the Red Hat Developers team and received a report that the ansible-playbook command doesn't execute in step 2 of the Ansible Web Server scenario: https://github.com/rhel-labs/learn-katacoda/blob/master/ansible-web-server/step2.md

**To reproduce**
- Visit step 2 of the scenario
- confirm that `cat apache.yml` runs
- try to execute the second command `ansible-playbook apache.yml`

**Expected behavior**
- command executes 

**Buggy behavior**
command line response is
```
[root@18044f96f87c ~]# ansible-playbook apache.yml
bash: ansible-playbook: command not found
```

I also tried to manually install ansible using the command here: https://github.com/rhel-labs/learn-katacoda/blob/master/ansible-web-server/background.sh

<img width="1124" alt="Screen Shot 2020-09-17 at 5 16 02 PM" src="https://user-images.githubusercontent.com/619297/93529716-62280300-f90a-11ea-9900-26176379b30f.png">

But that says the subscription has expired. Is there a particular account these accounts are registered to?

Thanks!

**Comment by smcbrien** [comment]
Hi Jon!  Thanks for reporting this.  We've engaged Katacoda (our back-end lab provider) and need them to make some changes to the images such that these boxes are subscribed to the correct account and have the right subscription entitlements.

-STM

**Comment by jonhorton** [comment]
Thanks @smcbrien! Happy to test things out or provide more info if needed 🎉

**Comment by smcbrien** [comment]
@jonhorton Ok, I got an updated image to test today, we've told them to push it to production.  Once that happens, I'll test it one more time and update this issue with an 'all clear'.

-STM

**Comment by jonhorton** [comment]
@smcbrien Thanks for the update—that's great news! Once I get the all clear, I'll update the customers that have reached out. Thanks so much for the help 🎉

**Comment by smcbrien** [comment]
@jonhorton I think this has been resolved now.  Thanks again for letting us know!

**Comment by smcbrien** [comment]
@jonhorton Looks like I spoke too soon.  the environment has been updated, but apparently is having issues provisioning.  Lab provider again notified.

**Comment by jonhorton** [comment]
@smcbrien Ahh nice catch! Was just testing it out and saw that it's hanging while provisioning the environment.

**Comment by smcbrien** [comment]
Ok, now really, really fixed!
