### ISSUE TITLE
vdo-configure

### ISSUE THREAD

**Issue by vijay24794** [rhel-labs/learn-katacoda#142]
[root@503a58d33027 ~]# vdostats --human-readable
VDOStatistics version mismatch
[root@503a58d33027 ~]#

**Comment by smcbrien** [comment]
vijay24794,

Thanks for reporting this issue!  The lab should now work as written.

The error you received was correct, there was a version mis-match between vdo (user space tools) and the kernel module.  You'll notice that in the very first command on step1 we install software for VDO and initially, while specifying the version number of the kernel module, we did not specify the version of VDO.  With the recent release of RHEL 8.3, the version of VDO was updated and the command on step1 was pulling the most recent version which is incompatible with the older 8.2-based kernel module we were using.

To resolve this, I added a specific version of vdo package (the one that came with RHEL 8.2) to install in the command in step1.  We're currently working on making an 8.3 image available for the labs and when that is released, I'll be revising the lab to be pinned to those newer versions of software, though the lab instructions themselves should remain unchanged.

All the best!

-STM
