### ISSUE TITLE
Creating system images with the Image Builder command line interface - Issues

### ISSUE THREAD

**Issue by someoldgituser** [rhel-labs/learn-katacoda#145]
In Step 1 .. 
yum -y install composer-cli lorax-composer  ...   lorax-composer actually installs osbuild-composer, this in turn tries to do :- 
systemctl enable --now lorax-composer.service

lorax-composer service doesnt exist but osbuilder does, this can be enabled .. 
In Step 2 

composer-cli blueprints list  - doesnt list any blue prints

**Comment by smcbrien** [comment]
Hi, I wanted to acknowledge the issue.

I've re-written the imagebuilder (using Web Console) lab to account for the change to osbuild-composer, but haven't had an opportunity to revise the CLI version of the lab.  I'll see what I can get done in the next week'ish.

-STM

**Comment by dpredhat** [comment]
Hello @someoldgituser 

Thank you for your feedback. We have updated the lab at https://lab.redhat.com/imagebuilder-cli 

Can you please take it for a spin, and let us know if you have any further feedback?

Thank you,

**Comment by dpredhat** [comment]
Closing this issue as there is no further feedback. Please re-open this issue if this is still a problem.
