### ISSUE TITLE
[Using Red Hat Insights, Advisor] insights dosn't reflect any advisories on the system 

### ISSUE THREAD

**Issue by mkbredem** [rhel-labs/learn-katacoda#149]
Step 3 of 6 doesn't align with the lab copy, because the system doesn't have any advisories.

**Comment by smcbrien** [comment]
@mkbredem I verified this today.  It looks like somehow the openssh configuration advisor recommendation we had been using is now fixed.  I'll work with the insights team to find a way to 'break' the system so that we get a recommendation to remediate again.

**Comment by smcbrien** [comment]
@mkbredem I think this is resolved now and the systems have resumed displaying the OpenSSH remediation suggestion outlined in the lab.
