### ISSUE TITLE
Configuring Terminal Session Recording  instance not entitled

### ISSUE THREAD

**Issue by mkbredem** [rhel-labs/learn-katacoda#150]
Step 1 of "Session Recording" on lab.redhat.com gives the following error:

Updating Subscription Management repositories.

This system is registered to Red Hat Subscription Management, but is not receiving updates. You can use subscription-manager to assign subscriptions.

Interestingly, I just tried to duplicate it and it worked.  There must be one particular instance that doesn't have a repo to install necessary packages.

**Comment by smcbrien** [comment]
@mkbredem I've not been able to reproduce the issue.  I did change the instances to use Simple Content Access about 3 weeks ago, so I think we can not have subscription issues anylonger.  YAY!
