### ISSUE TITLE
Unable to mount stratis and stratis snapshot

### ISSUE THREAD

**Issue by Be-Rahul** [rhel-labs/learn-katacoda#158]
URL- https://lab.redhat.com/stratis

o In below command /dev/ is missing which causes errors while mounting stratis FS and snapshot.

# stratis fs
Pool Name   Name    Used      Created             Device                       UUID                            
my_pool     my_fs   546 MiB   May 24 2021 20:02   /dev/stratis/my_pool/my_fs   6d1e7880f8f04dbba471b60a60b8b4ea
[root@70464161a30d ~]# mkdir /mnt/test_mnt
[root@70464161a30d ~]# mount /stratis/my_pool/my_fs /mnt/test_mnt
mount: /mnt/test_mnt: special device /stratis/my_pool/my_fs does not exist.

able to mount with below command:

# mount /dev/stratis/my_pool/my_fs /mnt/test_mnt                                        //Corrected command
[root@70464161a30d ~]# df | grep test_mnt
/dev/mapper/stratis-1-120bb54d19cb43ab9d5a9c530e63da7a-thin-fs-6d1e7880f8f04dbba471b60a60b8b4ea 1073217536 7517520 1065700016   1% /mnt/test_mnt
[root@70464161a30d ~]#

**Comment by smcbrien** [comment]
@Be-Rahul Thanks for opening the issue!  I found we had a similar problem on the following step as well where the /dev prefix device directory was missing.  I think there was a change in how stratis devices are represented to the machine in the latest 8.4 packages.

Thanks again!
