### ISSUE TITLE
buildah: Example Usecase refers to OCIFile

### ISSUE THREAD

**Issue by nalind** [rhel-labs/learn-katacoda#178]
The introductory text under "Example Usecase" mentions using OCIFile or Dockerfile.  Buildah and Podman currently look for "Containerfile" and "Dockerfile" by default, so someone who tried to put build instructions into a file named "OCIFile" and expected the tool to find it by default might be confused.

**Comment by smcbrien** [comment]
@nalind I've updated the nomenclature throughout the lab, introduction, step1, step2, and step5.

-STM

**Comment by nalind** [comment]
Thanks!  I was looking at the landing page (https://lab.redhat.com/buildah), though.

**Comment by smcbrien** [comment]
@nalind Looks like I forgot to commit the update there and it was missed by my git push.  Now all good?

**Comment by smcbrien** [comment]
I cleaned it up the phrasing a bit.  Going to close the issue since we've reconciled the "OCIFile" issue originally reported.
