### ISSUE TITLE
RHEL Content QA :: sql-server-ubi

### ISSUE THREAD

**Issue by dpredhat** [rhel-labs/learn-katacoda#258]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/rhel
Topic Page: 
Main Source Code: 

- [x] Run instruqt track validate command in the auto-migrated track folder
- [x] Go through the configuration file (config.yml) - delete multiple machine instances if not required by the lab
- [x] Go through the track_scripts/ folder to ensure that the[ track verify script i](https://docs.instruqt.com/tracks/lifecycle-scripts#track-setup-script )s migrated properly from background.sh
- [x] Go through the commands in the track.yml file 
- [x] Mark / add yourself as the new developer of the lab in the track.yml file
- [ ] Clean up assets such as image links by updating the paths to point to the absolute path instead of relative paths
- [ ] Open the track.yml file manually and replace open tick (`) in the execute line with ```
- [ ] Replace executes with 2 ticks: `sed -Ei 's/\{\{execute(.*)\}\}/``/g' track.yml `
- [ ] In the tabs section remote the RHEL web console service if it is not required by the lab
- [ ] Re-run instruqt track verify
- [ ] Run instruqt track push
- [ ] Manually re-verify all the steps in the instruqt page
- [ ] Optionally, if stuck, check instruqt track logs to ensure there are no issues
- [ ] Push the updated lab into github
- [ ] Mark this epic as complete

**Comment by myee111** [comment]
This lab is broken at step 6
