### ISSUE TITLE
[vdo/step 1] vdo package's version mismatch

### ISSUE THREAD

**Issue by kmoriwak** [rhel-labs/learn-katacoda#59]
related file: https://github.com/rhel-labs/learn-katacoda/blob/master/VDO-configure/step1.md

Problem:
"yum install -y vdo" will install the latest version of kmod-kvdo package.  But this lab environment's kernel a bit old and this lab cannot reboot.  It causes mismatch between running kernel and kmod-kvdo.

Reproducer:
1. launch vdo lab
2. yum install -y vdo
3. modprobe kvod -> causes error
4. compare "uname -r" and "rpm -ql kmod-kvdo" output

Background:
At 2019-08-07, there are two versions of kmod-kvdo.x86_64 packages in RHEL8. And the lab uses kernel-4.18.0-80.el8.
6.2.0.293-50.el8 -> this matches kernel-4.18.0-80.el8
6.2.0.293-52.el8 -> this matches kernel-4.18.0-80.7.1.el8_0

Suggestion:
For instant workaround, I suggest set versions like following. 
yum install -y vdo-6.2.0.293-10.el8 kmod-kvdo-6.2.0.293-50.el8

If keeping commands simple is important, you can make local yum repository.

**Comment by smcbrien** [comment]
I've updated the scenario to include specific versions of vdo and kmod-kvdo with the yum install.  The scenario now works as written.
